language: node_js
node_js:
  - 9
  - 8
before_install:
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
deploy:
  provider: npm
  email: rmamdaminov@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
